const nav=document.querySelector('.nav');const menuBtn=document.querySelector('.menu-btn');const links=document.querySelector('.nav-links');const back=document.querySelector('.backtop');
window.addEventListener('scroll',()=>{nav?.classList.toggle('scrolled',scrollY>20);back?.classList.toggle('show',scrollY>500)});
menuBtn?.addEventListener('click',()=>{links.classList.toggle('open');menuBtn.setAttribute('aria-expanded',links.classList.contains('open'))});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false')}));
back?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelectorAll('.tabs').forEach(tabs=>{const buttons=tabs.querySelectorAll('.tab-btn');const root=tabs.nextElementSibling;buttons.forEach(btn=>btn.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));btn.classList.add('active');root.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));root.querySelector(`#${btn.dataset.tab}`).classList.add('active')}))});

const lessonFilters=document.querySelectorAll('.lesson-filter');
lessonFilters.forEach(btn=>btn.addEventListener('click',()=>{lessonFilters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.lesson-card').forEach(card=>card.classList.toggle('hidden',btn.dataset.grade!=='all'&&card.dataset.grade!==btn.dataset.grade))}));

const demoData={
  cap1:{label:'Bài học Cấp 1',badge:'Toán lớp 2',title:'Chọn đáp án đúng',question:'24 + 18 bằng bao nhiêu?',answers:['32','42','52'],correct:1,explanation:'24 + 18 = 42. Em có thể cộng 20 + 10 rồi cộng tiếp 4 + 8.'},
  cap2:{label:'Bài học Cấp 2',badge:'Tiếng Anh lớp 8',title:'Complete the sentence',question:'The Thai people live mainly in ___ houses.',answers:['brick','stilt','glass'],correct:1,explanation:'“Stilt houses” là nhà sàn — kiểu nhà truyền thống phổ biến của người Thái.'},
  cap3:{label:'Bài học Cấp 3',badge:'Vật lý lớp 11',title:'Dao động điều hòa',question:'Đại lượng ω trong x = A cos(ωt + φ) là gì?',answers:['Biên độ','Tần số góc','Pha ban đầu'],correct:1,explanation:'ω là tần số góc, đơn vị rad/s và liên hệ với chu kỳ bởi ω = 2π/T.'}
};
let activeDemoGrade='cap1';
function setDemo(grade){const data=demoData[grade];if(!data)return;activeDemoGrade=grade;document.querySelectorAll('.demo-grade').forEach(b=>b.classList.toggle('active',b.dataset.demo===grade));const content=document.querySelector('#demo-content');if(!content)return;content.className=`demo-content demo-${grade}`;document.querySelector('#demo-label').textContent=data.label;content.querySelector('.demo-badge').textContent=data.badge;document.querySelector('#demo-title').textContent=data.title;document.querySelector('#demo-question').textContent=data.question;const answers=document.querySelector('#demo-answers');answers.classList.remove('answered');answers.innerHTML=data.answers.map((x,i)=>`<button data-answer="${i}">${x}</button>`).join('');const result=document.querySelector('#demo-result');if(result){result.className='demo-result';result.textContent=''}document.querySelector('#demo-retry')?.classList.remove('show')}
document.querySelectorAll('.demo-grade').forEach(btn=>btn.addEventListener('click',()=>setDemo(btn.dataset.demo)));
document.querySelectorAll('[data-demo-grade]').forEach(btn=>btn.addEventListener('click',()=>{setDemo(btn.dataset.demoGrade);document.querySelector('#demo')?.scrollIntoView({behavior:'smooth'})}));
document.querySelector('#demo-answers')?.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON'||e.currentTarget.classList.contains('answered'))return;const data=demoData[activeDemoGrade];const selected=Number(e.target.dataset.answer);e.currentTarget.classList.add('answered');e.currentTarget.querySelectorAll('button').forEach((b,i)=>{b.disabled=true;if(i===data.correct)b.classList.add('correct')});const result=document.querySelector('#demo-result');if(selected===data.correct){e.target.classList.add('correct');result.className='demo-result correct';result.innerHTML=`<strong>Chính xác!</strong> ${data.explanation}`}else{e.target.classList.add('wrong');result.className='demo-result wrong';result.innerHTML=`<strong>Chưa đúng.</strong> ${data.explanation}`}document.querySelector('#demo-retry')?.classList.add('show')});
document.querySelector('#demo-retry')?.addEventListener('click',()=>setDemo(activeDemoGrade));
document.querySelector('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('#form-note').textContent='Cảm ơn bạn! Biểu mẫu demo đã ghi nhận thông tin trên thiết bị này.';e.target.reset()});
